services:

  # 1. Backend Node.js Service
  backend:
    build: 
      context: ./backend
    container_name: elc_backend
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
      - CLIENT_ORIGIN=http://16.171.240.204
    networks:
      - elc_network

  # 2. Frontend React/Vite Service
  frontend:
    build:
      context: ./frontend
    container_name: elc_frontend
    ports:
      - "80:80" # Maps port 80 on your machine to port 80 in the Nginx container
    depends_on:
      - backend
    networks:
      - elc_network

# Define the network so the containers can communicate using their service names
networks:
  elc_network:
    driver: bridge